---

  # Latest version result: chiaLoganalyzerSourceGithubResult.recommended_version
- name: Determine Chia Loganalyzer latest release version
  maveno_source_github:
    owner: kubec
    repo: chia-log-analyzer
  environment:
    SSL_CERT_DIR: /etc/ssl/certs
    REQUESTS_CA_BUNDLE: "{{ mavenoSystemCaCertificatesFilePath }}"
  register: chiaLoganalyzerSourceGithubResult
  tags: utilities

- name: Download Chia Loganalyzer executable
  become: yes
  get_url:
    url: "https://github.com/kubec/chia-log-analyzer/releases/download/{{ chiaLoganalyzerSourceGithubResult.recommended_version }}/chia-log-analyzer.go-linux-{{ mavenoForksLogAnalyzerArchitectureLookupTable[mavenoSystemArchitecture] }}"
    dest: "{{ mavenoManagingHomeDirectory }}/.local/bin/chia-log-analyzer"
    owner: "{{ mavenoManagingSystemUsername }}"
    group: "{{ mavenoManagingSystemUsername }}"
    mode: 0755
  environment:
    SSL_CERT_DIR: /etc/ssl/certs
  register: getUrlResult
  until: getUrlResult is success
  retries: 10
  delay: 30
  tags: utilities

...
