---

  
- name: Assign Chia fork instance group to managing user
  become: true
  user:
    name: "{{ forksManagingSystemUsername|default('root') }}"
    groups: 
      - "{{ forkSystemUsernameItem }}"
    append: yes
  loop: >-
    {{ (forksComponentsConfigurationDescriptor|selectattr('username', 'defined')|map(attribute='username')
    + forksComponentsConfigurationDescriptor|selectattr('username', 'undefined')|map(attribute='fork'))|unique }}
  loop_control:
    loop_var: forkSystemUsernameItem


## Qwinns Forktools

#- name: Setup Qwinns Forktools
#  when: forksInstallForktools is defined
#  include_tasks: installForktools.yml
#  tags: utilities


...
