---


- name: Configure Fork Git nodes
  include_tasks: configure-git.yml
  loop: >-
    {{ (forksComponentsConfiguration
    | selectattr('host', 'equalto', inventory_hostname)
    | selectattr('build', 'undefined')
    + forksComponentsConfiguration
    | selectattr('host', 'equalto', inventory_hostname)
    | selectattr('build', 'defined')
    | selectattr('build', 'equalto', 'git')) }}
  loop_control:
    loop_var: forksComponentItem

- name: Configure Fork Docker Components
  vars:
    forksNodeForkIdentifier: "{{ forksComponentItem.fork }}"
  include_tasks: configure-docker.yml
  loop: >-
    {{ forksComponentsConfiguration
    | selectattr('host', 'equalto', inventory_hostname)
    | selectattr('build', 'defined')
    | selectattr('build', 'equalto', 'docker') }}
  loop_control:
    loop_var: forksComponentItem


  ## Commons
  
- name: Assign Chia fork instance group to managing user
  become: true
  user:
    name: "{{ forksManagingSystemUsername|default('root') }}"
    groups: 
      - "{{ forkSystemUsernameItem }}"
    append: yes
  loop: >-
    {{ (forksComponentsConfiguration|selectattr('host', 'equalto', inventory_hostname)
    | selectattr('username', 'defined')|map(attribute='username')
    + forksComponentsConfiguration|selectattr('host', 'equalto', inventory_hostname)
    | selectattr('username', 'undefined')|map(attribute='identifier'))|unique }}
  loop_control:
    loop_var: forkSystemUsernameItem


## Qwinns Forktools

#- name: Setup Qwinns Forktools
#  when: forksInstallForktools is defined
#  include_tasks: installForktools.yml
#  tags: utilities


...
