---


- name: Configure Fork Git nodes
  include_tasks: configure-git.yml
  loop: "{{ forksHostConfiguration }}"
  loop_control:
    loop_var: forksNodeConfiguration
  tags:
    - config
    - updates
    - aliases
    - backups
    - transporter


  ## Commons

- name: Configure Fork nodes ramdisk logging
  when: forksNodeConfiguration.build | default('git') == 'git'
  include_tasks:
    file: logging.yml
    apply:
      tags: logging
  loop: "{{ forksHostConfiguration }}"
  loop_control:
    loop_var: forksNodeConfiguration
  tags: logging

- name: Mount ramdisk(s) for Forks nodes logging
  become: true
  command: mount -a


- name: Create tempfile directory for certificates
  delegate_to: localhost
  tempfile:
    state: directory
  register: forksCertificatesTempfileResult
  changed_when: false
  run_once: true
  tags: certificates

- name: Distribute certs to Forks nodes
  when:
    - "'certs' in forksNodeConfiguration.keys()"
    - forksNodeConfiguration.build | default('git') == 'git'
  include_tasks:
    file: certificates.yml
    apply:
      tags: certificates
  loop: "{{ forksHostConfiguration }}"
  loop_control:
    loop_var: forksNodeConfiguration
  tags: certificates


- name: Restart Forks nodes services
  become: true
  systemd:
    name: "{{ forksNodeServiceName }}.service"
    daemon-reload: yes
    enabled: "{{ forksNodeEnabled }}"
    state: "{{ forksNodeEnabled | ternary('restarted', 'stopped') }}"
  changed_when: false
  loop: "{{ forksHostConfiguration }}"
  loop_control:
    loop_var: forksNodeConfiguration
  tags:
    - config
    - patches
    - logging
    - certificates


- name: Assign Chia fork instance group to managing users'
  become: true
  user:
    name: "{{ forksManagingSystemUsername | default('root') }}"
    groups: 
      - "{{ forksNodeSystemUsername }}"
    append: yes
  loop: "{{ forksHostConfiguration }}"
  loop_control:
    loop_var: forksNodeConfiguration


...
