---


## Backup config

- name: "Create config backup directory for Forks node {{ forksNodeIdentifier }}"
  become: true
  file:
    path: "{{ forksNodeHomeDirectory }}/.local/var/backup"
    state: directory
    owner: "{{ forksNodeSystemUsername }}"
    group: "{{ forksNodeSystemUsername }}"
    mode: 0750
  tags: config

- name: "Create backup of config file for Forks node {{ forksNodeIdentifier }}"
  become: true
  copy:
    src: >-
      {{ forksNodeHomeDirectory }}/{{
      forksNodeConfigurationDirectoryName
      }}/mainnet/config/config.yaml
    dest: >-
      {{ forksNodeHomeDirectory }}/.local/var/backup/config-{{
      ansible_date_time.iso8601 }}.yaml
    remote_src: true
    owner: "{{ forksNodeSystemUsername }}"
    group: "{{ forksNodeSystemUsername }}"
    mode: 0750
  tags: config


## Modify config

- name: "Fetch config data of Forks node {{ forksNodeIdentifier }}"
  when: "'config' in forksNodeConfiguration.keys()"
  become: true
  slurp:
    src: >-
      {{ forksNodeHomeDirectory }}/{{ 
      forksNodeConfigurationDirectoryName }}/mainnet/config/config.yaml
  register: nodeConfigSlurpResult
  tags: config

- name: "Store modified Fork config data for Forks node {{ forksNodeIdentifier }}"
  when: "'config' in forksNodeConfiguration.keys()"
  become: true
  vars:
    forkConfigurationData: "{{ nodeConfigSlurpResult['content'] | b64decode | from_yaml }}"
  copy:
    dest: >-
      {{ forksNodeHomeDirectory }}/{{
      forksNodeConfigurationDirectoryName }}/mainnet/config/config.yaml
    content: >-
      {{ forkConfigurationData | combine(forksNodeConfiguration.config
      | default({}), recursive=True) | to_yaml }}
    owner: "{{ forksNodeSystemUsername }}"
    group: "{{ forksNodeSystemUsername }}"
    mode: 0750
    force: true
  tags: config

  # HINT: Filter to_yaml appears messing up data types, here quoting port numbers making
  # them strings. Current verision Chia (1.7.0) will not run properly with port numbers
  # given as strings. Quotes in lines containing port numbers are stripped of quotes here.
- name: "Remove quotes in modified config file of Forks node {{ forksNodeIdentifier }}"
  when: "'config' in forksNodeConfiguration.keys()"
  become: true
  command: >-
    sed -i /{{ nodeConfigurationMatchTokenItem }}:/s/\'//g
    "{{ forksNodeHomeDirectory }}/{{
    forksNodeConfigurationDirectoryName }}/mainnet/config/config.yaml"
  loop:
    - host
    - port
  loop_control:
    loop_var: nodeConfigurationMatchTokenItem
  changed_when: false
  tags: config


  # Cronjobs

- name: "Adds paths to CA certs to crontab of Forks node {{ forksNodeIdentifier }}"
  when: whichCrontabCommandResult.rc == 0
  become: true
  cron:
    name: REQUESTS_CA_BUNDLE
    user: "{{ forksNodeSystemUsername }}"
    env: yes
    job: "{{ forksSystemCaCertificatesFilePath }}"

- name: "Adds certs path to crontab of Forks node {{ forksNodeIdentifier }}"
  when: whichCrontabCommandResult.rc == 0
  become: true
  cron:
    name: SSL_CERT_DIR
    user: "{{ forksNodeSystemUsername }}"
    env: yes
    job: /etc/ssl/certs


- name: "Setup auto-update for Forks node {{ forksNodeIdentifier }}"
  include_tasks: auto-update.yml
  tags: always


- name: "Generate service file for Forks node {{ forksNodeIdentifier }}"
  become: true
  template:
    src: fork-git.service.j2
    dest: "{{ forksSystemServiceDirectory }}/{{ forksNodeServiceName }}.service"
    force: true
    owner: root
    group: root
    mode: 0644


  ## Firewall

- name: "Allow node network traffic for Forks node {{ forksNodeIdentifier }}"
  when: 
    - "'services' in forksNodeConfiguration.keys()"
    - "'node' in forksNodeConfiguration.services"
  become: true
  ufw:
    rule: allow
    port: "{{ forksProperties[forkIdentifier]['nodePort'] }}"
    proto: tcp

- name: "Allow farmer network traffic for Forks node {{ forksNodeIdentifier }}"
  when: 
    - "'services' in forksNodeConfiguration.keys()"
    - >-
      'farmer' in forksNodeConfiguration.services
      or 'farmer-only' in forksNodeConfiguration.services
  become: true
  ufw:
    rule: allow
    port: "{{ forksProperties[forkIdentifier]['farmerPort'] }}"
    proto: tcp


- name: "Setup daily backups for Forks node {{ forksNodeIdentifier }}"
  include_tasks: daily-backup.yml
  tags: backups


# Aliases

- name: "Adding aliases to .bashrc of managing user for Forks node {{ forksNodeIdentifier }}"
  become: true
  blockinfile:
    path: "{{ forksManagingHomeDirectory | default('/root') }}/.bashrc"
    insertafter: '^#NON-INTERACTIVE.*'
    marker: "# {mark} {{ forksNodeIdentifier }} ALIASES"
    owner: "{{ forksManagingSystemUsername | default('root') }}"
    group: "{{ forksManagingSystemUsername | default('root') }}"
    mode: 0640
    block: |
      {{ forksNodeAlias }}() {
          sudo su - {{ forksNodeSystemUsername }} -c "{{
      forksNodeApplicationDirectory }}/venv/bin/{{ forksNodeExecutableName }} $*"
      }
      alias tail_{{ forksNodeAlias }}="sudo tail -f {{ forksNodeHomeDirectory }}/{{
      forksNodeConfigurationDirectoryName }}/mainnet/log/debug.log"
  tags: aliases


- name: Setup Plot Transporter
  when:
    - forksHostPlottingTargetDirectory is defined
    - forksHostPlotDirectories[forkIdentifier] | default([])
  vars:
    forksUtilsContextTransporterSourceDirectory: >-
      {{ forksHostPlottingTargetDirectory | default('undefined') }}
    forksUtilsContextTransporterTargetDirectories: >-
      {{ forksHostPlotDirectories[forkIdentifier] | default([]) }}
  include_role:
    name: maveno_de.forks.utilities
    tasks_from: setupPlotTransporter
  tags: transporter


...
