---


- name: "Enable user services for user {{ forkSystemUsername }}"
  become: yes
  shell: "loginctl enable-linger {{ forkSystemUsername }}"
  args:
    creates: "/var/lib/systemd/linger/{{ forkSystemUsername }}"

- name: Add Docker environment variables to context system user
  vars:
    contextBashRcFilePath: "{{ forkHomeDirectory }}/.bashrc"
    contextNonInteractiveRules:
      - export XDG_RUNTIME_DIR=/run/user/$(id -u)
      - export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock
  include_tasks: addNonInteractiveRulesToBashRc.yml


- name: "Install rootless docker for user {{ forkSystemUsername }}"
  become: yes
  become_user: "{{ forkSystemUsername }}"
  shell: dockerd-rootless-setuptool.sh install
  args:
    chdir: "{{ forkHomeDirectory }}"
    executable: /bin/bash
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
    DOCKER_HOST: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"    


...