---


- name: "Clone chia-docker repository for {{ forksComponentIdentifier|capitalize }}"
  become: true
  become_user: "{{ forksComponentSystemUsername }}"
  git:
    repo: https://github.com/maveno-de/forks-docker.git
    #version: "{{ forksComponentIdentifier }}-{{ forksArchitectureLookupTable[forksSystemArchitecture] }}"
    dest: "{{ forksComponentHomeDirectory }}/.local/share/forks-docker"
    force: yes
  environment:
    SSL_CERT_DIR: /etc/ssl/certs
    REQUESTS_CA_BUNDLE: "{{ forksSystemCaCertificatesFilePath }}"


- name: "Build {{ forksComponentIdentifier|capitalize }} docker image"
  when: not 'branch' in forksComponentItem
  become: true
  become_user: "{{ forksComponentSystemUsername }}"
  community.docker.docker_image:
    name: "{{ forksComponentIdentifier }}"
    build:
      nocache: yes
      path: "{{ forksComponentHomeDirectory }}/.local/share/chia-docker/src/{{ forksComponentApplicationDirectoryName }}"
      platform: "{{ forksPlatformLookupTable[forksSystemArchitecture] }}"
    source: build
    docker_host: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
  async: "{{ (1800 * forksJobTimeFactor)|int }}" # 30 mins * time factor
  poll: 0
  register: forkDockerImageBuildJob

- name: "Wait for {{ forksComponentIdentifier|capitalize }} docker image being built"
  when: not 'branch' in forksComponentItem
  become: true
  become_user: "{{ forksComponentSystemUsername }}"
  async_status:
    jid: "{{ forkDockerImageBuildJob.ansible_job_id }}"
  register: asyncStatusResult
  until: asyncStatusResult.finished
  retries: "{{ (90 * forksJobTimeFactor)|int }}" # 30 mins * time factor
  delay: 20

- name: "Build {{ forksComponentIdentifier|capitalize }} docker image ({{ forkBuildRequirementsDescriptor.branch }})"
  when: "'branch' in forksComponentItem"
  become: true
  become_user: "{{ forksComponentSystemUsername }}"
  community.docker.docker_image:
    name: "{{ forksComponentIdentifier }}"
    build:
      nocache: yes
      path: "{{ forksComponentHomeDirectory }}/.local/share/chia-docker/src/{{ forksComponentApplicationDirectoryName }}"
      platform: "{{ forksPlatformLookupTable[forksSystemArchitecture] }}"
      args:
        BRANCH: "{{ forkBuildRequirementsDescriptor.branch }}"
    source: build
    docker_host: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
  async: "{{ (1800 * forksJobTimeFactor)|int }}" # 30 mins * time factor
  poll: 0
  register: forkDockerImageBuildJob

- name: "Wait for {{ forksComponentIdentifier|capitalize }} docker image ({{ forkBuildRequirementsDescriptor.branch }}) being built"
  when: "'branch' in forksComponentItem"
  become: true
  become_user: "{{ forksComponentSystemUsername }}"
  async_status:
    jid: "{{ forkDockerImageBuildJob.ansible_job_id }}"
  register: asyncStatusResult
  until: asyncStatusResult.finished
  retries: "{{ (90 * forksJobTimeFactor)|int }}" # 30 mins * time factor
  delay: 20



- name: Start {{ forksComponentIdentifier|capitalize }} docker network
  become: true
  become_user: "{{ forksComponentSystemUsername }}"
  community.docker.docker_network:
    name: "{{ forksComponentIdentifier }}-network"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
    DOCKER_HOST: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"


  ## Fullnode/Wallet container

  #TODO: [WARNING]: Docker warning: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
- name: "Start {{ forksComponentIdentifier|capitalize }} fullnode+wallet container"
  when: forksComponentComponentType == 'fullnode+wallet'
  become: true
  become_user: "{{ forksComponentSystemUsername }}"
  community.docker.docker_container:
    name: "{{ forksComponentIdentifier }}-{{ forkRequirementsInstanceItem.name }}"
    image: "{{ forksComponentIdentifier }}:latest"
    hostname: "{{ forksComponentIdentifier }}.{{ forkRequirementsInstanceItem.name }}"
    state: "{{ (forkRequirementsInstanceItem.enabled|default(true))|ternary('started', 'stopped') }}"
    recreate: yes
    restart_policy: unless-stopped
    env:
      service: "{{ forksComponentComponentType }}"
      log_level: INFO
      keys: "/root/.{{ forksComponentIdentifier }}/mainnet/config/.mnemonics"
    networks:
      - name: "{{ forksComponentIdentifier }}-network"
    published_ports:
      - "{{ forkBuildRequirementsDescriptor.nodePort }}:{{ forkBuildRequirementsDescriptor.nodePort }}"
    volumes:
      - "{{ forksComponentHomeDirectory }}/.{{ forksComponentIdentifier }}-{{ forkRequirementsInstanceItem.name }}:/root/.{{ forksComponentIdentifier }}"
    container_default_behavior: no_defaults
    network_mode: "{{ forksComponentIdentifier }}-network"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
    DOCKER_HOST: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"   
  loop: "{{ forkBuildRequirementsDescriptor.instances }}"
  loop_control:
    loop_var: forkRequirementsInstanceItem


  ## Wallet container

- name: "Start {{ forksComponentIdentifier|capitalize }} wallet only container"
  when: forksComponentComponentType == 'wallet'
  become: true
  become_user: "{{ forksComponentSystemUsername }}"
  community.docker.docker_container:
    name: "{{ forksComponentIdentifier }}-{{ forkRequirementsInstanceItem.name }}"
    image: "{{ forksComponentIdentifier }}:latest"
    hostname: "{{ forksComponentIdentifier }}.{{ forkRequirementsInstanceItem.name }}"
    state: "{{ (forkRequirementsInstanceItem.enabled|default(true))|ternary('started', 'stopped') }}"
    recreate: yes
    restart_policy: unless-stopped
    env:
      service: "{{ forksComponentComponentType }}"
      fullnode_address: "{{ forksComponentIdentifier }}.{{ forkBuildRequirementsDescriptor.fullnodeName }}"
      log_level: INFO
      keys: "/root/.{{ forksComponentIdentifier }}/mainnet/config/.mnemonics"
    networks:
      - name: "{{ forksComponentIdentifier }}-network"
    volumes:
      - "{{ forksComponentHomeDirectory }}/.{{ forksComponentIdentifier }}-{{ forkRequirementsInstanceItem.name }}:/root/.{{ forksComponentIdentifier }}"
    container_default_behavior: no_defaults
    network_mode: "{{ forksComponentIdentifier }}-network"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
    DOCKER_HOST: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"   
  loop: "{{ forkBuildRequirementsDescriptor.instances }}"
  loop_control:
    loop_var: forkRequirementsInstanceItem


  ## Harvester container

- name: "Ensure {{ forksComponentIdentifier|capitalize }} CA cert(s) local directory"
  when: forksComponentComponentType == 'harvester'
  become: true
  file:
    path: "{{ forksComponentHomeDirectory }}/.{{ forksComponentIdentifier }}-{{ forkRequirementsInstanceItem.name }}-cacert"
    state: directory
    owner: "{{ forksComponentSystemUsername }}"
    group: "{{ forksComponentSystemUsername }}"
    mode: 0700
  loop: "{{ forkBuildRequirementsDescriptor.instances }}"
  loop_control:
    loop_var: forkRequirementsInstanceItem

- name: "Place {{ forksComponentIdentifier|capitalize }} CA cert(s) in local directory"
  when: forksComponentComponentType == 'harvester'
  vars:
    contextProductStoreAction: restore
    contextComponentIdentifier: "{{ forksComponentIdentifier }}"
    contextProductOrganization: "{{ forksVendorIdentifier }}"
    contextProductLabel: "ca_cert-{{ forkRequirementsInstanceItem.farmerAddress }}-{{ forksComponentIdentifier }}"
    contextProductDirectory: "{{ forksComponentHomeDirectory }}/.{{ forksComponentIdentifier }}-{{ forkRequirementsInstanceItem.name }}-cacert/ca"
    contextSystemUser: "{{ forksComponentSystemUsername }}"
  include_tasks: productStore.yml
  loop: "{{ forkBuildRequirementsDescriptor.instances }}"
  loop_control:
    loop_var: forkRequirementsInstanceItem
  tags: certificates

  #HINT: Double regex map due to bug of ansible map filter "xxx:xxx:"
- name: "Start {{ forksComponentIdentifier|capitalize }} harvester container"
  when: forksComponentComponentType == 'harvester'
  become: true
  become_user: "{{ forksComponentSystemUsername }}"
  community.docker.docker_container:
    name: "{{ forksComponentIdentifier }}-{{ forkRequirementsInstanceItem.name }}"
    image: "{{ forksComponentIdentifier }}:latest"
    hostname: "{{ forksComponentIdentifier }}.{{ forkRequirementsInstanceItem.name }}"
    state: "{{ (forkRequirementsInstanceItem.enabled|default(true))|ternary('started', 'stopped') }}"
    recreate: yes
    restart_policy: unless-stopped
    env:
      service: "{{ forksComponentComponentType }}"
      farmer_address: "{{ forkRequirementsInstanceItem.farmerAddress }}"
      farmer_port: "{{ forkRequirementsInstanceItem.farmerPort }}"
      plots_dir: "{{ (forkRequirementsInstanceItem.plotDirectories|default([]))|join(':') }}"
      ca: "/root/.{{ forksComponentIdentifier }}-cacert/ca"
      log_level: INFO
      keys: "copy"
    networks:
      - name: "{{ forksComponentIdentifier }}-network"
    volumes: "{{ [forksComponentHomeDirectory + '/.' + forksComponentIdentifier + '-' + forkRequirementsInstanceItem.name + '/:/root/.' + forksComponentIdentifier+'/'] + [forksComponentHomeDirectory + '/.' + forksComponentIdentifier + '-' + forkRequirementsInstanceItem.name + '-cacert/ca:/root/.' + forksComponentIdentifier+'-cacert/ca'] + (forkRequirementsInstanceItem.plotDirectories|default([]) | map('regex_replace', '(.*)', '\\1:\\1') | map('regex_replace', '(.*):', '\\1') | list) }}"
    container_default_behavior: no_defaults
    network_mode: "{{ forksComponentIdentifier }}-network"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
    DOCKER_HOST: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"   
  loop: "{{ forkBuildRequirementsDescriptor.instances }}"
  loop_control:
    loop_var: forkRequirementsInstanceItem
  tags: certificates


  #HINT: To prevent corruption of blockchain databases
- name: "Let {{ forksComponentIdentifier|capitalize }} instances come up"
  pause:
    seconds: 55


...
