---


  ## ## ##
  # RESULT:
  #  - forksNodeServiceStatusResult['status']['LoadState']|default('') == 'loaded'
  #  - forksNodeServiceStatusResult['status']['ActiveState']|default('') == 'active'
  #  - forksNodeServiceStatusResult['status']['LoadState']|default('') == 'not-found'
  #  - forksNodeServiceStatusResult['status']['ActiveState']|default('') == 'inactive'
- name: "Get service status of Forks node {{ forksNodeIdentifier }}"
  become: true
  systemd:
    name: "{{ forksNodeServiceName }}.service"
  register: forksNodeServiceStatusResult

- name: "Stop service of Forks node {{ forksNodeIdentifier }}"
  when:
    - forksNodeServiceStatusResult['status']['LoadState']|default('') == 'loaded'
    - forksNodeServiceStatusResult['status']['ActiveState']|default('') == 'active'
  become: true
  systemd:
    name: "{{ forksNodeServiceName }}.service"
    state: stopped

#- name: "Let Forks {{ forksNodeIdentifier }} service shutdown properly"
#  pause:
#    seconds: 4


  #RESULT: forksNodeLogFilesFindResult.files
- name: "Find log files of Forks node {{ forksNodeIdentifier }}"
  become: true
  find:
    paths: "{{ forksNodeHomeDirectory }}/{{ forksNodeConfigurationDirectoryName }}/mainnet/log"
  register: forksNodeLogFilesFindResult

- name: "Remove log files of Forks node {{ forksNodeIdentifier }}"
  become: true
  file:
    path: "{{ forksNodeLogFileItem.path }}"
    state: absent
  loop: "{{ forksNodeLogFilesFindResult.files }}"
  loop_control:
    loop_var: forksNodeLogFileItem


- name: "Unmount logging directory ram disk of Forks node {{ forksNodeIdentifier }}"
  become: true
  ansible.posix.mount:
    path: "{{ forksNodeHomeDirectory }}/{{ forksNodeConfigurationDirectoryName }}/mainnet/log"
    state: unmounted

- name: "Ensure logging directory as mount point of Forks node {{ forksNodeIdentifier }}"
  become: true
  file:
    path: "{{ forksNodeHomeDirectory }}/{{ forksNodeConfigurationDirectoryName }}/mainnet/log"
    state: directory
    owner: "{{ forksNodeSystemUsername }}"
    group: "{{ forksNodeSystemUsername }}"
    mode: 0750

- name: "Add ramdisk for logging to fstab file for Forks node {{ forksNodeIdentifier }}"
  become: true
  vars:
    forksNodeLogRamdiskSize: >-
      {{ ('node' in forksNodeConfiguration.services
      or forksProperties[forkIdentifier]['databaseVersion']
      | default(2) == 1)
      | ternary('50M', '20M') }}
  lineinfile:
    path: /etc/fstab
    line: >-
      tmpfs    {{ forksNodeHomeDirectory }}/{{ forksNodeConfigurationDirectoryName }}/mainnet/log    tmpfs    defaults,nofail,size={{
      forksNodeLogRamdiskSize }},uid={{ forksNodeSystemUsername }},gid={{
      forksNodeSystemUsername }},mode=0750    0    0
    state: present
    insertafter: EOF


- name: "Remove logging section from config of Forks node {{ forksNodeIdentifier }}"
  become: true
  ansible.builtin.blockinfile:
    path: "{{ forksNodeHomeDirectory }}/{{ forksNodeConfigurationDirectoryName }}/mainnet/config/config.yaml"
    marker: "# {mark} {{ forksNodeIdentifier }} LOGGING SECTION"
    state: absent

- name: "Remove Logging related lines from config of Forks node {{ forksNodeIdentifier }}"
  become: true
  lineinfile:
    path: "{{ forksNodeHomeDirectory }}/{{ forksNodeConfigurationDirectoryName }}/mainnet/config/config.yaml"
    regexp: >-
      ^.*{{ forksConfigLineItem }}.*$
    state: absent
    owner: "{{ forksNodeSystemUsername }}"
    group: "{{ forksNodeSystemUsername }}"
    mode: 0750
  loop:
    - 'logging:'
    - 'log_filename:'
    - 'log_level:'
    - 'log_maxbytesrotation:'
    - 'log_maxfilesrotation:'
    - 'log_stdout:'
    - 'log_syslog:'
    - 'log_syslog_host:'
    - 'log_syslog_port:'
  loop_control:
    loop_var: forksConfigLineItem
  tags: logging

- name: "Add logging section to config of Forks node {{ forksNodeIdentifier }}"
  become: true
  vars:
    forksNodeLogMaxBytesRotation: >-
      {{ ('node' in forksNodeConfiguration.services)
      | ternary('16777216', '6291456') }}
  ansible.builtin.blockinfile:
    path: "{{ forksNodeHomeDirectory }}/{{ forksNodeConfigurationDirectoryName }}/mainnet/config/config.yaml"
    insertbefore: BOF
    owner: "{{ forksNodeSystemUsername }}"
    group: "{{ forksNodeSystemUsername }}"
    mode: 0750
    marker: "# {mark} {{ forksNodeIdentifier }} LOGGING SECTION"
    block: |
      logging: &logging
        log_filename: log/debug.log
        log_level: INFO
        log_maxfilesrotation: {{
      forksProperties[forkIdentifier]['databaseVersion']
      | default(2) }}
        log_maxbytesrotation: {{ forksNodeLogMaxBytesRotation }}
        log_stdout: false
        log_syslog: false
        log_syslog_host: localhost
        log_syslog_port: 514

- name: "Add refs to logging section in config of Forks node {{ forksNodeIdentifier }}"
  become: true
  lineinfile:
    path: "{{ forksNodeHomeDirectory }}/{{ forksNodeConfigurationDirectoryName }}/mainnet/config/config.yaml"
    line: '  logging: *logging #{{ forksConfigLineItem }}'
    insertafter: >-
      ^{{ forksConfigLineItem }}:.*$
    owner: "{{ forksNodeSystemUsername }}"
    group: "{{ forksNodeSystemUsername }}"
    mode: 0750
  loop:
    - 'farmer'
    - 'full_node'
    - 'harvester'
    - 'introducer'
    - 'pool'
    - 'timelord'
    - 'timelord_launcher'
    - 'ui'
    - 'wallet'
  loop_control:
    loop_var: forksConfigLineItem
  tags: logging


  #RESULT: forksPromtailConfigFileStatResult.stat.exists
- name: "Check if Promtail Configuration is present for Forks node {{ forksNodeIdentifier }}"
  become: true
  stat:
    path: /etc/promtail/config.yml
  register: forksPromtailConfigFileStatResult

- name: Slurp Promtail config data
  when:
    - forksPromtailConfigFileStatResult.stat.exists
  become: true
  slurp:
    src: /etc/promtail/config.yml
  register: promtailConfigSlurpResult

- name: "Store modified Promtail config data for Forks node {{ forksNodeIdentifier }}"
  when:
    - forksPromtailConfigFileStatResult.stat.exists
    - >-
      forksPromtailConfigurationData.scrape_configs
      | selectattr('job_name', 'equalto', forksNodeIdentifier)
      | list | length == 0
  become: true
  vars:
    forksPromtailConfigurationData: "{{ promtailConfigSlurpResult['content'] | b64decode | from_yaml }}"
    forksPromtailNodeScrapeConfig: >-
      {'job_name': "{{ forksNodeIdentifier }}",
      'static_configs': [{'targets': ['localhost'],
      'labels': {'job': "{{ forkIdentifier }}",
      '__path__': "{{ forksNodeHomeDirectory }}/{{ forksNodeConfigurationDirectoryName }}/mainnet/log/debug.log",
      'host': "{{ inventory_hostname }}",
      'namespace': 'forks' } }]}
    forksPromtailConfigurationModificationData:
      scrape_configs: >-
        {{ forksPromtailConfigurationData.scrape_configs
        + [forksPromtailNodeScrapeConfig] }}
  copy:
    dest: /etc/promtail/config.yml
    content: "{{ forksPromtailConfigurationData | combine(forksPromtailConfigurationModificationData, recursive=True)|to_yaml }}"
    owner: "{{ forksNodeSystemUsername }}"
    group: "{{ forksNodeSystemUsername }}"
    mode: 0750
    force: true


- name: "Add Promtail group to system user of Forks node {{ forksNodeIdentifier }}"
  become: true
  user:
    name: promtail
    groups:
      - "{{ forksNodeSystemUsername }}"
    append: true


...
