---


- name: Gather information for Chia forks installation
  include_tasks: gather.yml


- name: Stop tunnels
  include_tasks: stop-tunnels.yml
  tags: tunnels

- name: Prepare Chia forks installation
  include_tasks: prepare.yml
  tags:
    - patches
    - tunnels

- name: Install Chia forks
  include_tasks: install.yml
  tags: patches


- name: Configure Chia forks installation
  include_tasks: configure.yml
  tags: always


...
