---


- name: Prepare Chia forks installation
  include_tasks: prepare.yml

- name: Install Chia forks
  include_tasks: install.yml


- name: Configure Chia forks installation
  include_tasks: configure.yml
  tags:
    - utilities
    - services


...
