---


- name: "Generate modified .bashrc for user {{ forksNodeSystemUsername }}"
  vars:
    contextSystemUsername: "{{ forksNodeSystemUsername }}"
    contextHomeDirectory: "{{ forksNodeHomeDirectory }}"
    contextUserPaths: 
      - "{{ forksNodeApplicationDirectory }}"
    contextNonInteractiveRules:
      - ". {{ forksNodeApplicationDirectory }}/venv/bin/activate"
  include_role:
    name: maveno_de.forks_collection.forks_utilities
    tasks_from: generateBashRc.yml



# - name: "Install additional apt packages for {{ forksComponentIdentifier|capitalize }}"
#   when: "'aptPackages' in forksComponentItem"
#   block:
# 
#     - name: Switch temporarily to system python
#       set_fact: 
#         tempPythonInterpreter: >-
#           {{ ansible_python_interpreter
#           | default(forksSystemPythonInterpreter) }}
#     - set_fact: 
#         ansible_python_interpreter: "{{ forksSystemPythonInterpreter }}"
#     ###
# 
#     - name: "Install additional apt packages for {{ forksComponentIdentifier|capitalize }}"
#       become: true
#       apt:
#         cache_valid_time: 10800
#         name: "{{ forkBuildRequirementsDescriptor.aptPackages }}"
# 
#     ###
#     - name: Switch back to framework python venv
#       set_fact: 
#         ansible_python_interpreter: "{{ tempPythonInterpreter }}"


## Backup

#- name: "Ensure {{ forksComponentIdentifier|capitalize }} backup data directory"
#  when: forksBackupDataDirectory is defined
#  become: true
#  file:
#    path: "{{ forksBackupDataDirectory }}/{{ forksComponentIdentifier }}"
#    state: directory
#    owner: "{{ forksManagingSystemUsername|default('root') }}"
#    group: "{{ forksManagingSystemUsername|default('root') }}"
#    mode: 0700



## Active farmers

#- name: Generate farmer status script
#  when:
#    - not forkFarmerStatusScriptCreated is defined
#    - "'farmer' in forksComponentService"
#  become: true
#  template:
#    src: show_farmers.sh.j2
#    dest: "{{ forksManagingHomeDirectory|default('/root') }}/.local/bin/show_farmers.sh"
#    force: true
#    owner: "{{ forksManagingSystemUsername|default('root') }}"
#    group: "{{ forksManagingSystemUsername|default('root') }}"
#    mode: 0755
#  tags: utilities

#- name: Adding alias for showing active farmers to shell of managing user
#  when:
#    - not forkFarmerStatusScriptCreated is defined 
#    - "'farmer' in forksComponentService"
#  become: true
#  lineinfile:
#    path: "{{ forksManagingHomeDirectory|default('/root') }}/.bashrc"
#    line: "alias show_farmers=\"{{ forksManagingHomeDirectory|default('/root') }}/.local/bin/show_farmers.sh\""
#    insertafter: '^#NON-INTERACTIVE.*'
#  tags: utilities

#- set_fact:
#    forkFarmerStatusScriptCreated: yes
#  when: "'farmer' in forksComponentService"
#  tags: utilities


## Node performance

#- name: Generate node performance script
#  when:
#    - not forkNodePerformanceScriptCreated is defined 
#    - "'fullnode' in forksComponentService"
#  become: true
#  template:
#    src: node_performance.py.j2
#    dest: "{{ forksManagingHomeDirectory|default('/root') }}/.local/bin/node_performance.py"
#    owner: "{{ forksManagingSystemUsername|default('root') }}"
#   group: "{{ forksManagingSystemUsername|default('root') }}"
#   mode: 0750
#  tags: utilities

#- set_fact:
#    forkNodePerformanceScriptCreated: yes
#  when: "'fullnode' in forksComponentService"
#  tags: utilities


...
