---


  # RESULT: forkUserIdShellResult.stdout
- name: "Get uid of {{ forkIdentifier|capitalize }} system user"
  become: true
  shell: "id -u {{ forkSystemUsername }} | cat"
  changed_when: false
  register: forkUserIdShellResult
  tags: certificates

- name: "Create {{ forkIdentifier|capitalize }} system user"
  when: forkUserIdShellResult.stdout == ''
  become: true
  user:
    name: "{{ forkSystemUsername }}"
    home: "{{ forkHomeDirectory }}"
    comment: "{{ forkIdentifier|capitalize }}"
    shell: /bin/bash

  # Due to ansible warning
- name: Ensure remote temp dir for ansible
  become: true
  file:
    path: "{{ forkHomeDirectory }}/.ansible/tmp"
    state: directory
    owner: "{{ forkSystemUsername }}"
    group: "{{ forkSystemUsername }}"
    mode: 0700

- name: "Set permissions on {{ forkIdentifier|capitalize }} home directory"
  become: true
  file:
    path: "{{ forkHomeDirectory }}"
    state: directory
    owner: "{{ forkSystemUsername }}"
    group: "{{ forkSystemUsername }}"
    mode: o=


  # TODO: Role is not idempotent with current when clause, stopping with error
  # when running on existing rootless docker in the corresponding user
  # HINT: Stopping all running containers to prevent timeouts
  # when building due to cpu time consumption
- name: "Remove rootless docker service for user {{ forkSystemUsername }}"
  # when: forkUserIdShellResult.stdout != ''
  include_tasks: remove-rootless.yml

- name: Prepare rootless docker service
  when: not forkRootlessDockerIsPrepared is defined
  include_tasks: "prepare-rootless-{{ mavenoForksDockerInstallationOption }}.yml"

- name: Set docker rootless prepared status
  set_fact:
    forkRootlessDockerIsPrepared: true


- name: "Generate .bashrc for {{ forkIdentifier|capitalize }} system user"
  vars:
    contextSystemUsername: "{{ forkSystemUsername }}"
    contextHomeDirectory: "{{ forkHomeDirectory }}"
    contextRemoveExistingFile: true
  include_tasks: generateBashRc.yml

- name: Ensure .ssh directory for {{ forkIdentifier|capitalize }} system user"
  become: true
  file:
    path: "{{ forkHomeDirectory }}/.ssh"
    state: directory
    owner: "{{ forkSystemUsername }}"
    group: "{{ forkSystemUsername }}"
    mode: 0700

- name: "Adding SSH public keys to user {{ forkSystemUsername }}"
  become: true
  authorized_key:
    user: "{{ forkSystemUsername }}"
    key: "{{ mavenoPublicSshKeys|map(attribute='sshkey')|join('\n') }}"
    exclusive: true


- name: "Ensure {{ forkIdentifier|capitalize }} local directories"
  become: true
  file:
    path: "{{ forkHomeDirectory }}/.local/{{ mavenoForksLocalDirectoryItem }}"
    state: directory
    owner: "{{ forkSystemUsername }}"
    group: "{{ forkSystemUsername }}"
    mode: 0750
  loop:
    - share
    - bin
  loop_control:
    loop_var: mavenoForksLocalDirectoryItem

  # RESULT: forkUserIdShellResult.stdout
- name: "Get uid of {{ forkIdentifier|capitalize }} system user"
  become: true
  command: "id -u {{ forkSystemUsername }}"
  changed_when: false
  register: forkUserIdShellResult
  tags: certificates


# rootless Docker

- name: Add Docker environment variables to context system user
  vars:
    contextBashRcFilePath: "{{ forkHomeDirectory }}/.bashrc"
    contextNonInteractiveRules:
      - export XDG_RUNTIME_DIR=/run/user/$(id -u)
      - export DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock
  include_tasks: addNonInteractiveRulesToBashRc.yml


- name: "Check Docker service for user {{ forkSystemUsername }}"
  become: true
  become_user: "{{ forkSystemUsername }}"
  systemd:
    name: docker
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
  register: forkDockerServiceStatusResult

- name: "Install rootless docker for {{ forkIdentifier|capitalize }}"
  when: forkDockerServiceStatusResult.status.ActiveState != 'active'
  include_tasks: install-rootless.yml


- name: "Create null profile file for {{ forkIdentifier|capitalize }} rootless Docker"
  become: true
  copy:
    content: '{}'
    dest: "{{ forkHomeDirectory }}/.config/docker/profile.json"
    owner: "{{ forkSystemUsername }}"
    group: "{{ forkSystemUsername }}"
    mode: 0644
    force: true

  # NOTE: Debian changed from cgroupsv1 to cgroupsv2 in bulleye
  # preventing docker OCI service to start. Corresponding parameter below
  # can eventually be removed.
- name: "Modify {{ forkIdentifier|capitalize }} rootless Docker service file"
  become: true
  replace:
    path: "{{ forkHomeDirectory }}/.config/systemd/user/docker.service"
    regexp: '^ExecStart=.*$'
    replace: >-
      ExecStart=/usr/bin/dockerd-rootless.sh
      --seccomp-profile
      {{ forkHomeDirectory }}/.config/docker/profile.json
      {% if ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 11 %}
      --exec-opt native.cgroupdriver=cgroupfs{% endif %}


- name: Restart {{ forkIdentifier|capitalize }} rootless Docker service
  become: true
  become_user: "{{ forkSystemUsername }}"
  systemd:
    name: docker.service
    daemon_reload: true
    state: restarted
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
  changed_when: false


# Backup

- name: "Ensure {{ forkIdentifier|capitalize }} container backup data directory"
  when:
    - mavenoForksBackupDataDirectory is defined
  become: true
  file:
    path: "{{ mavenoForksBackupDataDirectory }}/{{ forkIdentifier }}-{{ mavenoForksRequirementsInstanceItem.name }}"
    state: directory
    owner: "{{ mavenoManagingSystemUsername }}"
    group: "{{ mavenoManagingSystemUsername }}"
    mode: 0700
  loop: "{{ forkBuildRequirementsDescriptor.instances }}"
  loop_control:
    loop_var: mavenoForksRequirementsInstanceItem
  tags: services


# Wallet kicker

- name: Generate wallet kicker script template
  when:
    - not forkWalletKickerScriptDockerCreated is defined
    - "'wallet' in mavenoForksRequirementsInstanceItem.startOption"
  become: true
  template:
    src: wallet-kicker-docker.sh.j2
    dest: "{{ mavenoManagingHomeDirectory }}/.local/bin/wallet-kicker-docker.sh"
    force: true
    owner: "{{ mavenoManagingSystemUsername }}"
    group: "{{ mavenoManagingSystemUsername }}"
    mode: 0755
  loop: "{{ forkBuildRequirementsDescriptor.instances }}"
  loop_control:
    loop_var: mavenoForksRequirementsInstanceItem
  tags: services

- name: Set flag for wallet kicker script installation
  set_fact:
    forkWalletKickerScriptDockerCreated: true
  when: "'wallet' in mavenoForksRequirementsInstanceItem.startOption"
  loop: "{{ forkBuildRequirementsDescriptor.instances }}"
  loop_control:
    loop_var: mavenoForksRequirementsInstanceItem
  tags: services


...
