---


- name: "Ensure system user for Forks node {{ forksNodeIdentifier }}"
  become: true
  user:
    name: "{{ forksNodeSystemUsername }}"
    home: "{{ forksNodeHomeDirectory }}"
    shell: /bin/bash
    comment: "Forks node {{ forksNodeIdentifier }}"
    umask: '0027'

- name: Ensure remote temp dir for ansible
  become: true
  file:
    path: "{{ forksNodeHomeDirectory }}/.ansible/tmp"
    state: directory
    owner: "{{ forksNodeSystemUsername }}"
    group: "{{ forksNodeSystemUsername }}"
    mode: 0700


- name: Ensure .ssh directory for Forks node {{ forksNodeIdentifier }}"
  become: true
  file:
    path: "{{ forksNodeHomeDirectory }}/.ssh"
    state: directory
    owner: "{{ forksNodeSystemUsername }}"
    group: "{{ forksNodeSystemUsername }}"
    mode: 0700

- name: "Adding SSH public keys for Forks node {{ forksNodeIdentifier }}"
  when:
    - forksPublicSshKeys is defined
    - forksPublicSshKeys | length > 0
  become: true
  authorized_key:
    user: "{{ forksNodeSystemUsername }}"
    key: >-
      {{ forksPublicSshKeys | map(attribute='sshkey') | join('\n') }}
    exclusive: true


- name: "Ensure local directories for Forks node {{ forksNodeIdentifier }}"
  become: true
  file:
    path: "{{ forkLocalDirectoryItem }}"
    state: directory
    owner: "{{ forksNodeSystemUsername }}"
    group: "{{ forksNodeSystemUsername }}"
    mode: 0750
  loop:
    - "{{ forksNodeBinaryDirectory }}"
    - "{{ forksNodeSharedDirectory }}"
    - "{{ forksNodeTempDirectory }}"
  loop_control:
    loop_var: forkLocalDirectoryItem


...
