---


- name: Update local CA certs
  become: true
  shell: update-ca-certificates


  #HINT: Stopping all running services to prevent timeouts
  # when building due to cpu time consumption
- name: Stop Chia fork services
  vars:
    baremetalComponents: >-
     {{ (forksComponentsConfigurationDescriptor
     | selectattr('build', 'undefined')
     + forksComponentsConfigurationDescriptor
     | selectattr('build', 'defined')
     | selectattr('build', 'equalto', 'git'))
     | selectattr('host', 'equalto', inventory_hostname) }}
  become: true
  systemd:
    name: "{{ forkServiceNameItem }}.service"
    state: stopped
  changed_when: false
  failed_when: false
  loop: >-
    {{ (baremetalComponents|selectattr('serviceName', 'defined')|map(attribute='serviceName')
    + baremetalComponents|selectattr('serviceName', 'undefined')|map(attribute='fork'))|unique }}
  loop_control:
    loop_var: forkServiceNameItem


- name: Adding aliases for showing temp and CPU clock to shell of managing user (RPi only)
  when: >
    ansible_lsb.id == 'Raspbian'
    or 'raspi' in ansible_kernel and ansible_distribution == 'Ubuntu'
  become: true
  lineinfile:
    path: "{{ forksManagingHomeDirectory|default('/root') }}/.bashrc"
    line: "{{ forksCommandLineItem }}"
    insertbefore: BOF
  loop:
    - alias show_temp='watch -n 1 sudo vcgencmd measure_temp'
    - alias show_clock='watch -n 1 sudo vcgencmd measure_clock arm'
  loop_control:
    loop_var: forksCommandLineItem
  tags: utilities


- name: Ensure local directories for managing user
  become: true
  file:
    path: "{{ forksManagingHomeDirectory|default('/root') }}/.local/{{ forksLocalDirectoryItem }}"
    state: directory
    owner: "{{ forksManagingSystemUsername|default('root') }}"
    group: "{{ forksManagingSystemUsername|default('root') }}"
    mode: 0750
  loop:
    - bin
    - tmp
    - opt
    #- lib/fork.blockchain.root
    #- lib/fork.config.root
  loop_control:
    loop_var: forksLocalDirectoryItem
  tags: [utilities, services]

  
#- name: Install Chia Loganalyzer executable
#  include_tasks: buildLogAnalyzer.yml


- name: Switch temporarily to system python
  set_fact: 
    tempPythonInterpreter: "{{ ansible_python_interpreter }}"
- set_fact: 
    ansible_python_interpreter: "{{ forksSystemPythonInterpreter }}"
###

- name: Install required apt packages
  become: true
  apt:
    pkg:
      - acl
      - git
      - screen
      - xz-utils
      - sysstat
    state: latest
    cache_valid_time: 10800

##
- name: Switch back to framework python venv
  set_fact: 
    ansible_python_interpreter: "{{ tempPythonInterpreter }}"


#- name: Enable performance enhancements for RPi4
#  include_tasks: enhancePerformance.yml


## Backup

# - name: Ensure backup data directory
#   when: forksBackupDataDirectory is defined
#   become: true
#   file:
#     path: "{{ forksBackupDataDirectory }}"
#     state: directory
#     owner: "{{ forksManagingSystemUsername|default('root') }}"
#     group: "{{ forksManagingSystemUsername|default('root') }}"
#     mode: 0700
#   tags: services

# - name: Generate backup script template
#   when: forksBackupDataDirectory is defined
#   become: true
#   template:
#     src: backup-forks.sh.j2
#     dest: "{{ forksManagingHomeDirectory|default('/root') }}/.local/bin/backup-forks.sh"
#     force: yes
#     owner: "{{ forksManagingSystemUsername|default('root') }}"
#     group: "{{ forksManagingSystemUsername|default('root') }}"
#     mode: 0755
#   tags: services


...
