---


- name: Store location of current python venv
  set_fact:
    tempPythonInterpreter: "{{ ansible_python_interpreter }}"
- name: Switch temporarily to system python
  set_fact:
    ansible_python_interpreter: "{{ mavenoSystemPythonInterpreter }}"
# ###

  # Installation per apt

- name: Install Docker repo key
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Get architecture from dpkg
  when: ansible_facts['os_family'] == 'Debian'
  command: dpkg --print-architecture
  register: dkpgArchitectureShellResult
  changed_when: dkpgArchitectureShellResult.rc == 0

- name: Add Docker repository (Debian family)
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  apt_repository:
    repo: >-
      deb [arch={{ dkpgArchitectureShellResult.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
      https://download.docker.com/linux/{{ ansible_distribution|lower }}
      {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Install Docker system packages (Debian family)
  when: ansible_facts['os_family'] == 'Debian'
  become: true
  apt:
    pkg:

      - docker-ce
      - docker-ce-cli
      - containerd.io


- name: Install Docker system packages for rootless mode (Debian family)
  when:
    - ansible_facts['os_family'] == 'Debian'
    - forkSystemUsername != ''
  become: true
  apt:
    pkg: uidmap

- name: Install RPi extra modules (Ubuntu 21.10 RPi)
  when:
    - ansible_distribution == 'Ubuntu'
    - >
      ansible_distribution_version == '21.10'
      or ansible_distribution_major_version > '21'
    - "'raspi' in ansible_kernel"
  become: true
  apt:
    pkg:
      - linux-modules-extra-raspis

# ###
- name: Switch back to framework python venv
  set_fact:
    ansible_python_interpreter: "{{ tempPythonInterpreter }}"


- name: Install slirp4netns
  include_tasks: installSlirp4NetNs.yml

- name: Install fuse-overlayfs
  include_tasks: installFuseOverlayFs.yml


- name: Stop and disable system docker service
  become: true
  systemd:
    name: docker.service
    enabled: false
    state: stopped
    daemon_reload: true


...
