---


- name: Update local CA certs
  become: true
  command: update-ca-certificates
  register: updateCaCertsCommandResult
  changed_when: updateCaCertsCommandResult.rc == 0


  # HINT: Stopping all running services to prevent timeouts
  # when building due to cpu time consumption
- name: Stop Chia fork services
  when: forkBuildRequirementsDescriptor.buildOption == 'git'
  vars:
    forkBuildRequirementsDescriptor: "{{ mavenoForksBuildRequirementsDescriptor[mavenoForksForkItem] }}"
    forkIdentifier: "{{ mavenoForksForkItem }}"
    forkServiceName: "{{ forkBuildRequirementsDescriptor.serviceName|default(forkIdentifier) }}"
  become: true
  systemd:
    name: "{{ forkServiceName }}.service"
    state: stopped
  changed_when: false
  failed_when: false
  loop: "{{ mavenoForksBuildRequirementsDescriptor|list }}"
  loop_control:
    loop_var: mavenoForksForkItem


- name: Adding aliases for showing temp and CPU clock to shell of managing user
  when: >-
    ansible_lsb.id == 'Raspbian'
    or 'raspi' in ansible_kernel and ansible_distribution == 'Ubuntu'
  become: true
  lineinfile:
    path: "{{ mavenoManagingHomeDirectory }}/.bashrc"
    line: "{{ mavenoForksCommandLineItem }}"
    insertafter: '^#NON-INTERACTIVE.*'
  loop:
    - alias show_temp='watch -n 1 sudo vcgencmd measure_temp'
    - alias show_clock='watch -n 1 sudo vcgencmd measure_clock arm'
  loop_control:
    loop_var: mavenoForksCommandLineItem
  tags: utilities


- name: Ensure local directories for managing user
  become: true
  file:
    path: "{{ mavenoManagingHomeDirectory }}/.local/{{ mavenoForksLocalDirectoryItem }}"
    state: directory
    owner: "{{ mavenoManagingSystemUsername }}"
    group: "{{ mavenoManagingSystemUsername }}"
    mode: 0750
  loop:
    - bin
    - tmp
    - opt
    - lib/fork.blockchain.root
    - lib/fork.config.root
  loop_control:
    loop_var: mavenoForksLocalDirectoryItem
  tags: [utilities, services]


- name: Install Chia Loganalyzer executable
  include_tasks: buildLogAnalyzer.yml


- name: Store location of current python venv
  set_fact:
    tempPythonInterpreter: "{{ ansible_python_interpreter }}"
- name: Switch temporarily to system python
  set_fact:
    ansible_python_interpreter: "{{ mavenoSystemPythonInterpreter }}"
# ###

- name: Install required apt packages
  become: true
  apt:
    pkg:
      - acl
      - git
      - screen
      - xz-utils
      - sysstat
    cache_valid_time: 10800

# ###
- name: Switch back to framework python venv
  set_fact:
    ansible_python_interpreter: "{{ tempPythonInterpreter }}"


- name: Enable performance enhancements for RPi4
  include_tasks: enhancePerformance.yml


# Backup

- name: Ensure backup data directory
  when: mavenoForksBackupDataDirectory is defined
  become: true
  file:
    path: "{{ mavenoForksBackupDataDirectory }}"
    state: directory
    owner: "{{ mavenoManagingSystemUsername }}"
    group: "{{ mavenoManagingSystemUsername }}"
    mode: 0700
  tags: services

- name: Generate backup script template
  when: mavenoForksBackupDataDirectory is defined
  become: true
  template:
    src: backup-forks.sh.j2
    dest: "{{ mavenoManagingHomeDirectory }}/.local/bin/backup-forks.sh"
    force: true
    owner: "{{ mavenoManagingSystemUsername }}"
    group: "{{ mavenoManagingSystemUsername }}"
    mode: 0755
  tags: services


...
