---


- name: Fix permissions for local docker directory
  become: true
  file:
    path: "{{ forkHomeDirectory }}/.local/share/docker"
    recurse: true
    follow: false
    owner: "{{ forkSystemUsername }}"
    group: "{{ forkSystemUsername }}"
    mode: u=rwX,g=rX,o=

- name: "Get {{ forkIdentifier|capitalize }} running containers"
  become: true
  become_user: "{{ forkSystemUsername }}"
  community.docker.docker_host_info:
    containers: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
    DOCKER_HOST: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"
  changed_when: false
  failed_when: false
  ignore_errors: true
  register: forkDockerHostInfoResult

- name: "Stop {{ forkIdentifier|capitalize }} running containers"
  when: "'containers' in forkDockerHostInfoResult.keys()"
  become: true
  become_user: "{{ forkSystemUsername }}"
  community.docker.docker_container:
    name: "{{ mavenoForksContainerItem }}"
    state: stopped
    container_default_behavior: no_defaults
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
    DOCKER_HOST: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"
  loop: "{{ forkDockerHostInfoResult.containers | map(attribute='Id') | list }}"
  loop_control:
    loop_var: mavenoForksContainerItem


- name: "Remove rootless docker for user {{ forkSystemUsername }}"
  become: true
  become_user: "{{ forkSystemUsername }}"
  command: dockerd-rootless-setuptool.sh uninstall
  args:
    chdir: "{{ forkHomeDirectory }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ forkUserIdShellResult.stdout }}"
    DOCKER_HOST: "unix:///run/user/{{ forkUserIdShellResult.stdout }}/docker.sock"
  register: removeRootlessDockerCommandResult
  failed_when: false
  changed_when: removeRootlessDockerCommandResult.rc == 0

- name: Remove docker data for user {{ forkSystemUsername }}"
  become: true
  file:
    path: "{{ forkHomeDirectory }}/.local/share/docker"
    state: absent

- name: Disable services for context user
  become: true
  command: "loginctl disable-linger {{ forkSystemUsername }}"
  args:
    removes: "/var/lib/systemd/linger/{{ forkSystemUsername }}"


...
