---


- name: Setup Forks Tunnel
  vars:
    tunnelsTargetNodeJsonQuery: >-
      [?value.forksHostConfiguration[?identifier=='{{
      forksTunnelItem.target }}'].identifier]
    forksTunnelContextTunnelIdentifier: "{{ forksTunnelItem.target }}"
    forksTunnelContextSourceHostname: "{{ inventory_hostname }}"
    forksTunnelContextSourceSystemUsername: "{{ forksNodeSystemUsername }}"
    forksTunnelContextSourceHomeDirectory: "{{ forksNodeHomeDirectory }}"
    forksTunnelContextTargetHostname: >-
      {{ (hostvars | dict2items
      | json_query(tunnelsTargetNodeJsonQuery))[0]['key'] }}
    forksTunnelContextTunnelPorts: "{{ forksTunnelItem.ports }}"
  include_role:
    name: maveno_de.forks.tunnel
    apply:
      tags: tunnels
  loop: >-
    {{ forksNodeConfiguration.tunnels }}
  loop_control:
    loop_var: forksTunnelItem
  tags: tunnels


...
