#!/bin/bash
set -e
UBUNTU=false
DEBIAN=false
if [ "$(uname)" = "Linux" ]; then
	#LINUX=1
	if type apt-get; then
		OS_ID=$(lsb_release -is)
		if [ "$OS_ID" = "Debian" ]; then
			DEBIAN=true
		else
			UBUNTU=true
		fi
	fi
fi

# Check for non 64 bit ARM64/Raspberry Pi installs
if [ "$(uname -m)" = "armv7l" ]; then
  echo ""
	echo "WARNING:"
	echo "The Skynet Blockchain requires a 64 bit OS and this is 32 bit armv7l"
	echo "For more information, see"
	echo "https://github.com/SkynetNetwork/skynet-blockchain/wiki/Raspberry-Pi"
	echo "Exiting."
	exit 1
fi
# Get submodules
git submodule update --init mozilla-ca

UBUNTU_PRE_2004=false
if $UBUNTU; then
	LSB_RELEASE=$(lsb_release -rs)
	# In case Ubuntu minimal does not come with bc
	if [ "$(which bc |wc -l)" -eq 0 ]; then sudo apt install bc -y; fi
	# Mint 20.04 repsonds with 20 here so 20 instead of 20.04
	UBUNTU_PRE_2004=$(echo "$LSB_RELEASE<20" | bc)
	UBUNTU_2100=$(echo "$LSB_RELEASE>=21" | bc)
fi

find_python() {
	set +e
	unset BEST_VERSION
 	for V in 39 3.9 38 3.8 37 3.7 3; do
		if which python$V >/dev/null; then
			if [ "$BEST_VERSION" = "" ]; then
				BEST_VERSION=$V
			fi
		fi
	done
	echo $BEST_VERSION
	set -e
}

if [ "$INSTALL_PYTHON_VERSION" = "" ]; then
	INSTALL_PYTHON_VERSION=$(find_python)
fi

# This fancy syntax sets INSTALL_PYTHON_PATH to "python3.7", unless
# INSTALL_PYTHON_VERSION is defined.
# If INSTALL_PYTHON_VERSION equals 3.8, then INSTALL_PYTHON_PATH becomes python3.8

INSTALL_PYTHON_PATH=python${INSTALL_PYTHON_VERSION:-3.7}

echo "Python version is $INSTALL_PYTHON_VERSION"
$INSTALL_PYTHON_PATH -m venv venv
if [ ! -f "activate" ]; then
	ln -s venv/bin/activate .
fi

# shellcheck disable=SC1091
. ./activate
# set pip timeout = 100
export PIP_DEFAULT_TIMEOUT=100
# pip 20.x+ supports Linux binary wheels
python -m pip install --upgrade pip
python -m pip install wheel
#if [ "$INSTALL_PYTHON_VERSION" = "3.8" ]; then
# This remains in case there is a diversion of binary wheels
python -m pip install --extra-index-url https://pypi.skynet-network.org/v01/ miniupnpc==2.2.2 --no-cache-dir
python -m pip install -e . --extra-index-url https://pypi.skynet-network.org/v01/ --no-cache-dir

SKYNET_VER=$(git tag --sort version:refname | tail -1)

echo ""
echo "................................................................................
................................................................................
....................................#%%%%%%%%...................................
..................................#####%%%%%%%%.................................
.................................#######%%%%%%%%................................
................................#########%%%%%%%%...............................
..............................#############%%%%%%%%.............................
.............................#######,#######%%%%%%%%............................
...........................########///########%%%%%%%(..........................
..........................########/////########%%%%%%%%.........................
.........................#######////////.#######%%%%%%%%........................
.......................########////////...########%%%%%%%%......................
......................########///////......,#######%%%%%%%%.....................
....................########////////.........#######*%%%%%%%*...................
...................########////////...........(#######%%%%%%%%..................
.................,########///////%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%.................
................########////////%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%...............
...............########///////////////////////////////////////////..............
.................####///////////////////////////////////////////................
..................##///////////////////////////////////////////.................
................................................................................
..............................  version_$SKYNET_VER  .................................
................................................................................
.....................@..............................................@...........
...........@@@@@@@...@.....@@@..@......@...@@@@@@@...../@@@@@#...@@@@@@@........
..........@@.........@..@@@.....@......@...@@.....@@..@@.....@@.....@...........
.................@&..@...@@.....@......@...@@.....@@..@@............@...........
..........@@@@@@@....@.....@@@...@@@@@.@...@@.....@@....@@@@@@......@...........
.................................@@@@@@@........................................
................................................................................
................................................................................
..................   Skynet blockchain install.sh complete   ...................
................................................................................
...........   Type '. ./activate' and then 'skynet init' to begin   ............
................................................................................
.....   To install the GUI type 'sh install-gui.sh' after '. ./activate'   .....
................................................................................
"